### PR TITLE
NLP apps notebook

### LINKED ISSUE #16: Notebook to demonstrate NLP applications
Create `nlp_apps.ipynb` to demonstrate NLP applications

### PR DESCRIPTION
**Pull request by utkarsh23**
Resolved #16 
This PR creates an IJulia notebook for NLP applications and demonstrates language recognition.

### CODE REVIEW

**Comment by mikhail-j** [comment]
@utkarsh23 Change the local variable type to use `AbstractCountingProbabilityDistribution`? Make sure the variable is of the correct type when using predict().

i.e.
```Julia
local attribute_distribution::AbstractCountingProbabilityDistribution = nbsm.attributes_distributions[target];
```

Overall, good work on the IJulia NLP apps notebook.

**Comment by utkarsh23** [comment]
@mikhail-j done :+1:

**Comment by utkarsh23** [comment]
Please do not merge this PR just yet. #18 needs to be resolved first after which I might have to update paths to the submodule `aima-data`.

**Comment by utkarsh23** [comment]
#18 is closed. You can now merge this PR. :+1:

**Pull request merged**
